### ISSUE TITLE
CRAN v2

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#132]
Once `see` is there, I think we can push bayestestR. The few things that potentially might be addressed / can be improved are:

- [x] brms BFs in `describe_posterior` #64 
- [x] diagnostic edgecase #129 
- [x] GAM models  #134 
- [x] `describe_prior.brmsfit` [here](https://github.com/easystats/insight/issues/105)
- [x] improved printing (especially for `pd`) so that it nicely displays dataframes #74 
- [x] Review/spellcheck of the new articles and documentation
- [x] ...

This release is an important milestone in the API stabilization process. After that (for v3 and beyond), we will be able to focus on documentation and dissemination (publications #36 #11) 🙌

**Comment by strengejacke** [comment]
Don't forget to update the NEWS file ;-)

**Comment by DominiqueMakowski** [comment]
> Don't forget to update the NEWS file ;-)

We worked too hard, too much to say 😞 🔫

**Comment by DominiqueMakowski** [comment]
I've added the main things, is there anything major more?

**Comment by strengejacke** [comment]
> bayesfactor() function has been added

There is no `bayesfactor()` in bayestestR ;-)

**Comment by DominiqueMakowski** [comment]
> There is no bayesfactor() in bayestestR ;-)

I meant [this](https://github.com/easystats/bayestestR/pull/140/commits/27c9fcc2cd014f1b109770cbad963dace5ce1bd8) NEWS file 😬

**Comment by strengejacke** [comment]
I haven't checked all docs yet, but we should see that at least one example is running. We could probably use a very quick compiling and running model:

```r
library(rstanarm)
model <- stan_glm(mpg ~ wt + gear, data = mtcars, chains = 2, iter = 200)
```

**Comment by DominiqueMakowski** [comment]
good idea

**Comment by DominiqueMakowski** [comment]
Well, anything on the TODO list that we want do have for v2 or we can delay the rest (printing etc.) to v3?

**Comment by mattansb** [comment]
All the BF functions are ready to go 👍👍👍

My only remaining concern is about ROPE doc/warning (#144) - but this is not really a functionality thing, right? Should we delay any decision on this for v3 / a small v2.0.0.1-sort-of patch?

**Comment by DominiqueMakowski** [comment]
> My only remaining concern is about ROPE doc/warning (#144) - but this is not really a functionality thing, right? Should we delay any decision on this for v3 / a small v2.0.0.1-sort-of patch?

Yes, ROPE functions have been implemented this way in sjstats, psycho and all for a long time, so any changes in that would have to be heavily discussed/documented/justified and advertised anyway so it won't make it for v2 for sure :)

Don't hesitate to skim through the documentation (vignettes and docstrings) again in search of typos/rephrasings and such!

**Comment by mattansb** [comment]
> Yes, ROPE functions have been implemented this way in sjstats, psycho and all for a long time [...]

Good point ^_^

**Comment by strengejacke** [comment]
> Well, anything on the TODO list that we want do have for v2 or we can delay the rest (printing etc.) to v3?

We have already usable print-methods, I guess, but the "unified" printing requires the forthcoming update of insight, anyway. Or are there any print-methods that need some polishing?

**Comment by strengejacke** [comment]
@DominiqueMakowski I have tweaked the print() method from `pd()` a bit, what do you think? Furthermore, I formatted the formula in the docs imn html for online-help. Please check the formula, as p_one sided_ and p_two sided_ are identical, is this intended?

**Comment by DominiqueMakowski** [comment]
Nice catch for the docs, I am revising it so it is more in line with the vignette.

For the printing method, awesome. But I think the end goal would be for it to look more like the printing of `hdi` or `rope` (i.e., a table look rather than a bullet list look).

**Comment by strengejacke** [comment]
I'm aware of your cognitive dissonance regarding non-passing Travis checks ;-) But currently, bayestestR performs quite well (three checks passed, two running, one failing). The failing check is osx-devel, which seems to be a current problem on Travis-side.

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/58471100-b2a7aa00-8175-11e9-9a37-81cdd24260e8.png)

**Comment by strengejacke** [comment]
Once we see if it passes Linux devel, we can do that.

**Comment by strengejacke** [comment]
ok, bayestestR passes all checks (5/6), except osx-devel, which. however, fails due to installing problems on Travis-side.

> 279.42s$ brew update >/dev/null
3.99s$ curl -fLo /tmp/R.pkg https://r.research.att.com/el-capitan/R-devel/R-devel-el-capitan-signed.pkg
curl: (22) The requested URL returned error: 404 Not Found

**Comment by DominiqueMakowski** [comment]
so, should I submit to CRAN tomorrow?  I think every main point is pretty much addressed (thanks for the pd printing)

**Comment by strengejacke** [comment]
I spotted three minor things, which you can decide to leave for 0.3.0 or address before submission
1) In [this vignette, section sensivity](https://easystats.github.io/bayestestR/articles/region_of_practical_equivalence.html#sensitivity-to-the-parameters-scale) the sampling-output from rstanarm could be hidden
2) docs for [rope_range()](https://easystats.github.io/bayestestR/reference/rope_range.html), section _Details_: we have a list here, maybe we could use bullet points instead of line breaks?
3) Should we add a sentence or reference on sensivity to the `rope()` docs as well? Copy/paste from the vignette? If adding the vignette into the docs, make sure **not** to include the `\href()` tag in the `@params`, but only to the references.

**Comment by strengejacke** [comment]
Should we add a point to the NEWS that plotting functions now require the _see_ pkg?

**Comment by mattansb** [comment]
> 4. Should we add a point to the NEWS that plotting functions now require the see pkg?

I think this would be a useful!

**Comment by strengejacke** [comment]
Note that on CRAN model-download for testing does not always work, and thus checks may fail (from time to time?): https://cran.r-project.org/web/checks/check_results_insight.html

**Comment by DominiqueMakowski** [comment]
I have addressed all of the points mentioned above. I think we are ready for a submission :) Let's go 🚀

**Comment by DominiqueMakowski** [comment]
The following error is on linux:

https://win-builder.r-project.org/incoming_pretest/bayestestR_0.2.0_20190529_063632/Debian/00check.log

```
  ── 1. Error: (unknown) (@test-bayesfactor.R#62)  ───────────────────────────────
  Service Unavailable (HTTP 503).
```` 

It looks like related to what you mentioned above. The CRAN reviewer said:

> "Packages which use Internet resources should fail gracefully with an 
informative message if the resource is not available (and not give a 
check warning nor error). "
> Please fix and resubmit.

How did you address this? We could add a `skip_on_CRAN()` in the test chunk

**Comment by strengejacke** [comment]
> "Packages which use Internet resources should fail gracefully with an
informative message if the resource is not available (and not give a
check warning nor error). "
Please fix and resubmit.

Maybe there's a misunderstanding here, because it's just a test, nothing which users have to do with. But anyway, this is how I addressed this in _insight_, ensuring that tests run locally and on travis, but not on CRAN:

```r
# test-xyz.R
.runThisTest <- Sys.getenv("RunAllinsightTests") == "yes"

if (.runThisTest || Sys.getenv("USER") == "travis") {
  # all your testthat-stuff
}
```

and in the file `/tests/testthat.R`:

```r
library(testthat)
library(insight)

if (length(strsplit(packageDescription("insight")$Version, "\\.")[[1]]) > 3) {
  Sys.setenv("RunAllinsightTests" = "yes")
} else {
  Sys.setenv("RunAllinsightTests" = "no")
}

test_check("insight")
```

However, you need version numbers with 4 parts for development, like **0.2.1.9** or so.

**Comment by DominiqueMakowski** [comment]
Isn't it easier to use [`skip_on_cran()`](https://rdrr.io/cran/testthat/man/skip.html) tho 🤔

**Comment by strengejacke** [comment]
It depends. You need to add this to each test-block.

**Comment by DominiqueMakowski** [comment]
Right, for insight is clearly not easier. For bayestestR it should work there are only 3 chunks where we download stuff

**Comment by DominiqueMakowski** [comment]
Should I resubmit bayestestR?

**Comment by strengejacke** [comment]
I just saw, since you opened Pandora's box...

`Prior_Scale` or `ROPE_Equivalence` also need to be renamed (https://github.com/easystats/parameters/issues/44#issuecomment-496815505)... You removed the "noun" rule that preserved capital letters for nouns! :-P

**Comment by DominiqueMakowski** [comment]
ah crap! Maybe this rule made sense tho...? I don't know what to do 😱 

Let's imagine the data frame in a manuscript. One way of easily improving the rendering could be for instance to simply replace the underscores by whitespaces. But then, what should a column name be (in a final manuscript), "Prior Scale" or "Prior scale"?

**Comment by strengejacke** [comment]
What would you expect as column header? 

...

Probably the second as lower case, as you suggested? Which means some annoying work...

**Comment by DominiqueMakowski** [comment]
Wouldn't you expect column names as "titles" though, with each noun capitalized?

**Comment by strengejacke** [comment]
I think a rule capitalising nouns is okay! That would mean you can revert the last changes.

**Comment by DominiqueMakowski** [comment]
haha. That's why we should use the dev branch

**Comment by DominiqueMakowski** [comment]
Greenlight for CRAN re-submission?

**Comment by mattansb** [comment]
`bayestestR` (v1) made it to [top 40 new CRAN packages](https://www.r-bloggers.com/april-2019-top-40-new-cran-packages/)!

**Comment by DominiqueMakowski** [comment]
Wow! That's awesome!! It deserves a tweet :)

**Comment by mattansb** [comment]
Done (:

**Comment by pdwaggoner** [comment]
This is incredible! Super exciting. Great work on this you guys.
