### ISSUE TITLE
Order restricted BF with multi-level factors

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#229]
This is an addendum to the [*testing order restricted BFs* vignette](https://easystats.github.io/bayestestR/articles/bayes_factors.html#order-restricted-models) regarding ***Order restricted BF with multi-level factors***. (It is too long and technical to include in the main vignette...)

# Background

If we want to test some order restriction among 3 groups A, B, and C, what is the *a priori* probability of obtaining the order A > C > B? It is 1/6 (reach back to intro to stats year 1...). And so when testing and order restriction on the ordering of levels in a factor, we would the priors or be 1/6.... But...

For our example, we will be interested in the following order restrictions in the `iris` data:
```R
hyp <- c(
  # comparing 2 levels
  "setosa > versicolor",
  "setosa > virginica",
  "versicolor > virginica",
  # comparing 3 (or more) levels
  "setosa    < virginica  & virginica  < versicolor",
  "virginica < setosa     & setosa     < versicolor",
  "setosa    < versicolor & versicolor < virginica"
)
```

For this demo we will need:
``` r
library(bayestestR)
library(rstanarm)
library(emmeans)
# we will also need bfrms
```

## With default factor coding

```R
fit <- stan_glm(Sepal.Length ~ Species, data = iris,
                family = gaussian())
em_ <- emmeans(fit, ~Species)
em_ # the posterior marginal means
#>  Species    emmean lower.HPD upper.HPD
#>  setosa       5.01      4.87      5.15
#>  versicolor   5.93      5.78      6.07
#>  virginica    6.59      6.44      6.73
#> 
#> HPD interval probability: 0.95 

bayesfactor_restricted(em_, fit, hypothesis = hyp)
#> # Bayes Factor (Order-Restriction)
#> 
#>                                        Hypothesis P(Prior) P(Posterior)  Bayes Factor
#>                               setosa > versicolor     0.50            0      0.00e+00
#>                                setosa > virginica     0.50            0      0.00e+00
#>                            versicolor > virginica     0.50            0      0.00e+00
#>  setosa    < virginica  & virginica  < versicolor     0.12            0      0.00e+00
#>  virginica < setosa     & setosa     < versicolor     0.25            0      0.00e+00
#>   setosa    < versicolor & versicolor < virginica     0.13            1          7.46
#> 
#> * Bayes factors for the restricted movel vs. the un-restricted model.
```

What happened???
1. The comparison of 2 levels all have a prior of 0.5, as expected.
2. The comparison of 3 levels has different priors, depending on the order restriction - i.e. **some orders are *a priori* more likely than others!!!**

You can read more about why this happens in [Rouder *et al* (2012,  section 7.2)](https://doi.org/10.1016/j.jmp.2012.08.001), but for now, let's focus on the solution...

## With projected factor coding

All you have to do is add this to the beginning of your script (from [`bfrms`](https://github.com/bayesstuff/bfrms)):
```R
contr.bayes <- bfrms::contr.bayes
options(contrasts = c('contr.bayes', 'contr.poly'))
```

And then run your analyses as usual:
```
fit <- stan_glm(Sepal.Length ~ Species, data = iris,
                family = gaussian())
em_ <- emmeans(fit, ~Species)
em_ # the posterior marginal means
#>  Species    emmean lower.HPD upper.HPD
#>  setosa       5.01      4.86      5.16
#>  versicolor   5.94      5.78      6.07
#>  virginica    6.59      6.45      6.73
#> 
#> HPD interval probability: 0.95 

bayesfactor_restricted(em_, fit, hypothesis = hyp)
#> # Bayes Factor (Order-Restriction)
#> 
#>                                        Hypothesis P(Prior) P(Posterior)  Bayes Factor
#>                               setosa > versicolor     0.51            0      0.00e+00
#>                                setosa > virginica     0.50            0      0.00e+00
#>                            versicolor > virginica     0.50            0      0.00e+00
#>  setosa    < virginica  & virginica  < versicolor     0.16            0      0.00e+00
#>  virginica < setosa     & setosa     < versicolor     0.17            0      0.00e+00
#>   setosa    < versicolor & versicolor < virginica     0.16            1          6.11
#> 
#> * Bayes factors for the restricted movel vs. the un-restricted model.
```

As we can see:
1. The estimated means are identical in both cases.
2. The comparison of 2 levels in both cases has the proper prior of 0.5.
3. The comparison of 3 levels has the proper prior in the second case only.

## TODO

- [ ] add bf_params example to the vignette
- [ ] add `contr.bayes` in the NOTRUN example of bf_params (with emmeans) + mention in the doc.
- [ ] add `contr.bayes` in the NOTRUN example of bf_restrict + mention in the doc.
- [ ] add `contr.bayes` to bayestestR?

**Comment by singmann** [comment]
@mattansb No problem. The only constraint is that the code was written by both me and @quentingronau, so we both would need to be added as contributors.
I am also not sure I am missing the point here, but I do not see a problem if you use the name `contr.bayes`. In contrast, changing it to `contr.bayesian` seems to be a bit confusing as then there are two identical functions, but with different names. But this of course your decision.

**Comment by mattansb** [comment]
@singmann great - will add you both! Thanks!

@DominiqueMakowski what do you think about the name? As maintainer... (:

**Comment by strengejacke** [comment]
Probably it's better to stick with `contr.bayes`. I think Dominiques concern was about user confusion due to warning messages when both packages are loaded and one package masks functions from another package.

**Comment by DominiqueMakowski** [comment]
> I think Dominiques concern was about user confusion due to warning messages

yes. but if Henrik and Quentin are okay with re-using the same name in bayestestR, then I guess it's okay :) 

@singmann @quentingronau happy to have you :muscle:

**Comment by mattansb** [comment]
Thanks everyone!
